import { matthew, royd, sully } from "@/public/assets";
import Image from "next/image";
import React from "react";

const Testimonial = () => {
  return (
    <div className="flex flex-col items-center gap-8">
      <div className="uppercase text-slate-500 tracking-widest text-sm font-semibold">
        Hear from our customers
      </div>
      <div className="flex items-stretch gap-8 flex-wrap justify-center">
        <div className="flex flex-col gap-4 justify-between text-sm max-w-lg">
          <div className="relative bg-blue-50 p-8 rounded flex flex-col items-center gap-2 prose-sm">
            <p>
              The challenge that the scale of AI chat brings is understanding
              which needle to look for in the haystack.
            </p>
            <p>
              <span className="font-semibold">
                Context.ai immediately gave me what I needed
              </span>
              : Data that I could use to close more sales and insights for
              engineering to improve the user experience.
            </p>
          </div>
          <div className="flex gap-4 items-center">
            <Image
              className="rounded-full max-w-16 min-w-16 border p-1 my-0"
              src={royd}
              alt="testimonial"
              layout="responsive"
              width={500}
              height={300}
              objectFit="contain"
            />
            <div className="name">
              <span className="font-semibold">Rod Smyth</span> <br />
              CEO &amp; Co-Founder at Glyde Talent
            </div>
          </div>
        </div>
        <div className="flex flex-col justify-between gap-4 max-w-lg text-sm">
          <div className="prose relative bg-blue-50 grow rounded p-8 flex items-center">
            <p>
              Context.ai gives us confidence that changes will perform well
              before we ship them to production, and then shows their
              performance with real users - this is incredibly helpful.
            </p>
          </div>
          <div className="flex gap-4 items-center">
            <Image
              className="rounded-full max-w-16 min-w-16 border p-1 my-0"
              src={matthew}
              alt="matthew superflows"
              layout="responsive"
              width={500}
              height={300}
              objectFit="contain"
            />
            <div className="name">
              <span className="font-semibold">Matthew Phillips</span> <br />
              CEO &amp; Co-Founder at Superflows
            </div>
          </div>
        </div>
        <div className="flex flex-col justify-between gap-4 max-w-lg text-sm">
          <div className="prose relative bg-blue-50 grow rounded p-8 text-sm">
            <p>
              We struggled to gain meaningful insights from the large amounts of
              data generated by our platform. It was difficult to understand
              exactly how users were interacting with the system and what they
              were trying to accomplish.
            </p>
            <p>
              With Context.ai, we are able to derive more insights into how
              users interact with our product. This has been huge for
              understanding our users better, so we can focus on the areas that
              matter.
            </p>
          </div>
          <div className="flex gap-4 items-center">
            <Image
              className="rounded-full max-w-16 min-w-16 border p-1 my-0"
              src={sully}
              alt="sully"
              layout="responsive"
              width={500}
              height={300}
              objectFit="contain"
            />
            <div className="name">
              <span className="font-semibold">Sully Omar</span> <br />
              CEO &amp; Co-Founder at Cognosys
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Testimonial;
